### ISSUE TITLE
Coloring ignored files in the Project View NOT WORKING in pyCharm 2019.2

### ISSUE THREAD

**Issue by v8877788** [JetBrains/idea-gitignore#598] opened 2019-08-03 14:09 UTC
### Prerequisites

* [ ] Plugin is in the latest version
* [ ] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Steps to Reproduce

1. _First Step_
2. _Second Step_
3. _and so on..._

**Expected behavior:**

**Actual behavior:** 

**Reproduces how often:** 

### Versions

**Plugin:** 

**IDE:** 

**OS:**

**Comment by dmitriysmirnovjb** [comment] 2019-08-04 21:09
Works fine for me - Git and Mercurial ignores are colored by the platform, in olive. Other ignores supported by the plugin, are colored in gray.

Please provide more details - a screenshot to start with.
What VCS do you use? Maybe you have not updated the plugin to 3.2.0?

**Comment by hsz** [comment] 2019-08-05 19:43
Duplicate of #592 
Please read https://github.com/JetBrains/idea-gitignore/issues/592#issuecomment-518369673 for more information regarding the problem, workaround and releasing the fix.

**Closed by hsz** 2019-08-05 19:43 UTC
Labels: bug, duplicate
