### ISSUE TITLE
IDEA EAP version is not available

### ISSUE THREAD

**Issue by tonycody** [JetBrains/idea-gitignore#609] opened 2019-11-10 00:56 UTC
IDEA EAP version is not available

![image](https://user-images.githubusercontent.com/6773121/68537016-fa269900-0397-11ea-93c3-a781752fe5d1.png)

**Comment by dmitriysmirnovjb** [comment] 2019-11-10 12:41
Duplicate of #603

**Closed by dmitriysmirnovjb** 2019-11-10 12:41 UTC
