### ISSUE TITLE
Add blank line when template does not end in newline

### ISSUE THREAD

**Issue by bamapookie** [JetBrains/idea-gitignore#398] opened 2017-07-31 14:52 UTC
Minor feature request: When adding a template, if the upstream .gitignore template does not end in newline, add one when generating the .gitignore file.

**Comment by hsz** [comment] 2017-07-31 15:00
@bamapookie Thanks for that - seems reasonable.
Do you have any example of the template that has no new line at the end?

**Comment by bamapookie** [comment] 2017-07-31 15:14
Not off hand.  I usually insert the blank line myself when I notice it.  Will update when I find one.  Another option would be to request some QC upstream.

**Comment by bamapookie** [comment] 2017-07-31 15:15
macOS template is one.

**Comment by toolforger** [comment] 2017-10-23 11:25
-1 here.

You do not know what the line end should look like: LF? CRLF? You can look in the file, but what if the file contains a mixture? What if the file is empty, or a single line without a line end?
The more you try to deal with edge cases, the more you have opportunities for the code to do things that the user did not expect.

(Aside note: Even without the CRLF conundrums, I'd recommend against doing this. If something unexpected happens, mechanisms like the one proposed here add yet another place that you have to check whether it might be responsible. This is a general caveat against behaviour that is out of scope - and modifying files just when they are read is definitely out of scope. Having standard line endings after the ignore file has been rewritten is a different issue, here people expect changes to the ignore file.)

**Comment by bamapookie** [comment] 2018-04-04 13:57
@toolforger This isn't a request to modify an untouched file.  This is a request to add a newline to the .ignore file along with a template when adding a template to an ignore file.

For example:  Suppose I have a .gitignore file with some nodeJS excludes and I want to add the macOS template and the JetBrains template to the file.  When I add them, since the macOS template does not end with a newline, the next template is added immediately after the macOS template with no break.

The solution would be to detect that the macOS template does not end with a newline and add it when applying the template to the .gitignore file.

**Comment by toolforger** [comment] 2018-04-04 14:25
Agreed, I got carried away.
Still, the point that a tool shouldn't modify the content of the file. If the upstream .gitignore does not have a final EOL, then it's the upstream .gitignore that should be corrected. It might make sense to issue a warning, but silently changing what got copied over is just complicating user-visible behaviour, it is surprising, and it is likely to as often create as fix a problem.
(Is a .gitignore without a line feed on the last line even a problem?)

**Comment by bamapookie** [comment] 2018-04-08 21:08
You are correct that fixing the template upstream would be better, but inserting a blank line at the end upon insertion would not be any worse than adding the comment line with the template name at the top.

**Comment by toolforger** [comment] 2018-04-08 21:38
Invisible changes are much harder to diagnose as the cause of a problem, so I assume it _is_ somewhat worse.
Note that problems can occur if the .gitignore file is processed by software other than git. E.g. if it's being inlined into a HTML file, or style checked, or something I don't think about right now.

**Closed** 2019-09-30 05:52 UTC
Labels: feature request, wontfix
