### ISSUE TITLE
Global gitignore is not indexable

### ISSUE THREAD

**Issue by JoshuaBehrens** [JetBrains/idea-gitignore#601] opened 2019-08-20 08:46 UTC
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet (#186 has different stacktrace)
* [x] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

Since a recent update I get errors logged that my global .gitignore file (which excludes .idea for example) is un-indexable. Restarting or cache invalidation has been tried unsuccessfully.

```
Error while indexing /home/joshua/.gitignore
To reindex this file IDEA has to be restarted

java.lang.IllegalStateException: psiFile is null. language = Git, substitutedLanguage = Git
	at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:151)
	at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:140)
	at com.intellij.util.indexing.FileContentImpl.getFileFromText(FileContentImpl.java:108)
	at com.intellij.util.indexing.FileContentImpl.getPsiFileForPsiDependentIndex(FileContentImpl.java:276)
	at com.intellij.util.indexing.FileContentImpl.getPsiFile(FileContentImpl.java:96)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.map(IgnoreFilesIndex.java:86)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.map(IgnoreFilesIndex.java:59)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:313)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:108)
	at com.intellij.util.indexing.impl.MapReduceIndex.calculateUpdateData(MapReduceIndex.java:269)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:251)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1673)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$28(FileBasedIndexImpl.java:1603)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:634)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1562)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1549)
	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$indexFiles$0(UnindexedFilesUpdater.java:109)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$0(CacheUpdateRunner.java:219)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$1(CacheUpdateRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:232)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Steps to Reproduce

1. Have a global .gitignore
2. Use this plugin
3. Load a project with git support enabled

**Expected behavior:**

.gitignore being indexed and applied to project like colored path nodes in the project view

**Actual behavior:** 

Error logs are stated by PhpStorm that it is not working with my global .gitignore (as stated above). Local .gitignore still works fine.

**Reproduces how often:** 

100%

### Versions

**Plugin:** 

3.2.1.192

**IDE:** 

```
PhpStorm 2019.2
Build #PS-192.5728.108, built on July 24, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-159-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 906M
Cores: 4
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: PlantUML integration, String Manipulation, com.github.gtache.lsp, com.intellij.ideolog, de.yannik_sc.java.intelli_j.plugins.unitize, mobi.hsz.idea.gitignore, net.seesharpsoft.intellij.plugins.csv, com.dmarcotte.handlebars, com.jetbrains.lang.ejs, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.laravel, de.espend.idea.php.annotation, net.king2500.plugins.PhpAdvancedAutoComplete, fr.adrienbrault.idea.symfony2plugin, de.espend.idea.shopware, org.psliwa.idea.composer, ru.adelf.idea.dotenv
```

**OS:** 

```
Linux 4.4.0-159-generic #187-Ubuntu SMP Thu Aug 1 16:28:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

My global .gitignore. Filename changed for github.
[gitignore.txt](https://github.com/JetBrains/idea-gitignore/files/3519527/gitignore.txt)

**Comment by dmitriysmirnovjb** [comment] 2019-08-20 09:22
Duplicate of #593

**Closed by dmitriysmirnovjb** 2019-08-20 09:22 UTC

**Comment by JoshuaBehrens** [comment] 2019-08-20 11:24
Snap. Sorry I didn't see that.
