### ISSUE TITLE
Please add support for new PhpStorm EAP

### ISSUE THREAD

**Issue by b1rdex** [JetBrains/idea-gitignore#582] opened 2019-05-23 05:29 UTC
It says plugin is incompatible and tries to downgrade to 2.6:
![image](https://user-images.githubusercontent.com/312855/58227753-83f19400-7d6f-11e9-80e1-7f10cf345a7c.png)

PhpStorm 2019.2 EAP
Build #PS-192.4205.18, built on May 22, 2019
Runtime version: 11.0.3+12-b262.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by hazarin** [comment] 2019-05-23 06:23
Yeah fix it please

**Comment by hsz** [comment] 2019-05-23 06:49
For now, plugin supports builds `192<`.
First of all, I'll have to test it across the 192 build and I'll get back to you soon.

**Comment by KestL** [comment] 2019-06-19 09:36
Any news about testing?

**Comment by ktomk** [comment] 2019-06-20 09:32
Works for me .ignore 2.6.2 with PhpStorm 2019.2 EAP; Build #PS-192.5118.33, built on June 13, 2019, I don't see the reported picture.

**Comment by dmitriysmirnovjb** [comment] 2019-07-29 11:16
Duplicate of #587

**Comment by dmitriysmirnovjb** [comment] 2019-07-29 11:17
Please see 587 for details

**Closed by dmitriysmirnovjb** 2019-07-29 11:16 UTC
