### ISSUE TITLE
.ignore version 3.1.2.191 incompatible with the current IntejjiJ IDEA version 2019.2

### ISSUE THREAD

**Issue by zb315044652** [JetBrains/idea-gitignore#588] opened 2019-07-26 07:16 UTC
.ignore version 3.1.2.191 incompatible with the current IntejjiJ IDEA version 2019.2

**Comment by pfalomorblab** [comment] 2019-07-26 07:38
@zb315044652 as @dmitriysmirnovjb said on for webstorm https://github.com/JetBrains/idea-gitignore/issues/587#issuecomment-514275657 there will be an update that fix this issue. Since IDEA (and other Intellij IDEs) implements more and more native support for .gitignore there will be overlap between the plugin and the core implementation. 

I guess we just need to wait. It would be awesome to know when will be released the update.

**Comment by dmitriysmirnovjb** [comment] 2019-07-29 10:52
Duplicate of #587

**Comment by dmitriysmirnovjb** [comment] 2019-07-29 10:53
We plan to release a plugin version compatible with 2019.2 this week. Please follow #587

**Closed by dmitriysmirnovjb** 2019-07-29 10:52 UTC
