### ISSUE TITLE
Incompatible with the latest IntelliJ IDEA 2019.2

### ISSUE THREAD

**Issue by BothyWong** [JetBrains/idea-gitignore#591] opened 2019-07-31 12:39 UTC
### Prerequisites

* [ ] Plugin is in the latest version
* [ ] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Steps to Reproduce

1. _First Step_
2. _Second Step_
3. _and so on..._

**Expected behavior:**

**Actual behavior:** 

**Reproduces how often:** 

### Versions

**Plugin:** 

**IDE:** 

**OS:**

**Comment by hsz** [comment] 2019-07-31 12:55
Duplicate of #587 
Please go to this ticket for more details.

**Closed by hsz** 2019-07-31 12:55 UTC
