### ISSUE TITLE
right click donot show 'add to ignore file'

### ISSUE THREAD

**Issue by learnprogram2** [JetBrains/idea-gitignore#590] opened 2019-07-30 10:09 UTC
right click on one file, it don't show 'add to ignore file', only show 'show ignored files'.
    when open 'setting'->'appearance&behavior'->'menus and toolbars', edit 'scope view popup menue'-> 'project view popup menu' , can see 'add to ignore file', but it's icon was a 'folder' icon.
    i m confused

**Comment by hsz** [comment] 2019-07-30 10:10
@learnprogram2 Please follow the issue template.

**Comment by inside-the-sandbox** [comment] 2019-08-01 14:45
I noticed that the .ignore plugin is not supported by Intellij 2019.2

**Comment by dmitriysmirnovjb** [comment] 2019-08-01 15:06
Ignore plugin is indeed not compatible with 2019.2 yet, see #587

**Comment by dmitriysmirnovjb** [comment] 2019-09-03 12:08
Duplicate of #587

**Closed by dmitriysmirnovjb** 2019-09-03 12:08 UTC
