### ISSUE TITLE
Need outer excludes back

### ISSUE THREAD

**Issue by cognivator** [JetBrains/idea-gitignore#701] opened 2021-05-20 01:17 UTC
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [X] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name - NA

### Description

I use the outer exclude links all the time. Both files are hidden, and neither are easy to navigate to in the folder structure. Having a quick edit for both is part of the 'killer' in this killer app.

### Steps to Reproduce

Open the primary `.gitignore` file and look for the outer exclude links in the editor.

**Expected behavior:**

Editor shows links to 'outer exclude' files - `exclude` in the `.git` subfolder, and the global gitignore file somewhere in the path to root, or the user home directory.

**Actual behavior:** 

No links.

**Reproduces how often:** 

Alla time.

### Versions

**Plugin:** 

```
4.1.x
```

**IDE:** 

```
2021.1.x
```

**OS:** 

```
MacOS 10.14.x
```

### Additional Information

NA

**Comment by hsz** [comment] 2021-05-20 21:08
Duplicate of #673

**Closed by hsz** 2021-05-20 21:08 UTC
Labels: duplicate, wontfix
