### ISSUE TITLE
IllegalStateException while indexing

### ISSUE THREAD

**Issue by rherrick** [JetBrains/idea-gitignore#593] opened 2019-08-02 18:08 UTC
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [X] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

```
Error while indexing /Users/rherrick/Development/XNAT/1.7/plugins/xnat-template-plugin/.gitignore
To reindex this file IDEA has to be restarted

java.lang.IllegalStateException: psiFile is null. language = Git, substitutedLanguage = Git
	at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:151)
	at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:140)
	at com.intellij.util.indexing.FileContentImpl.getFileFromText(FileContentImpl.java:108)
	at com.intellij.util.indexing.FileContentImpl.getPsiFileForPsiDependentIndex(FileContentImpl.java:276)
	at com.intellij.util.indexing.FileContentImpl.getPsiFile(FileContentImpl.java:96)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.map(IgnoreFilesIndex.java:86)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.map(IgnoreFilesIndex.java:59)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:313)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:108)
	at com.intellij.util.indexing.impl.MapReduceIndex.calculateUpdateData(MapReduceIndex.java:269)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:251)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1673)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$28(FileBasedIndexImpl.java:1603)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:634)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1562)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1549)
	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$indexFiles$0(UnindexedFilesUpdater.java:109)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$0(CacheUpdateRunner.java:219)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$1(CacheUpdateRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:232)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Steps to Reproduce

1. Imported an existing Gradle project into IntelliJ IDEA (existing project but hadn't been imported into the IDE previously).
2. Saw the warning lit indicating an exception.

The **.gitignore** file in the project contained the following:

```
*.iml
*.log
.classpath
.gradle*
.idea/
.project
.settings/
bin
build/
dep*.txt
gradle.properties
ide-bin/
lib/
out/
```

**Expected behavior:**

No exception.

**Actual behavior:** 

An exception occurred.

**Reproduces how often:** 

~~It happened one time. I copied the project to a new folder, changed the artifact name, and imported the new one and it didn't throw the exception.~~

Actually it seems to be happening a _lot_, it's just not always showing up with the alert in the IDE. I've attached 
[the log file with multiple errors in it](https://github.com/JetBrains/idea-gitignore/files/3462473/ignore-idea-log.zip).

### Versions

**Plugin:** 

```
3.2.0.192
```

**IDE:** 

```
IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.98, built on July 22, 2019
Licensed to Washington University School of Medicine in St. Louis / Rick Herrick
Subscription is active until November 22, 2019
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: bigger.font.in.project.view=true, external.system.substitute.library.dependencies=true, ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: A move tab left and right using the keyboard plugin - by momomo.com, A prevent pinned tabs from closing plugin - by momomo.com, Builder Generator, CheckStyle-IDEA, FindBugs-IDEA, GrepConsole, Lombook Plugin, RegexPlugin, Scratch, color.scheme.GapStyle, com.alayouni.ansiHighlight, com.daylerees.rainglow, com.facebook.rucinskic.chromaterial, com.intellij.ideolog, com.jensteichert.themes.nightowl, com.jetbrains.darkPurpleTheme, com.jetbrains.plugins.ini4idea, com.therdnotes, com.thvardhan.gradianto, com.tobszarny.activetabhighlighter.plugin.id, com.vermouthx.idea, com.atlassian.bitbucket.references, io.codearte.props2yaml, jms-messenger, mobi.hsz.idea.gitignore, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, org.antlr.intellij.plugin, org.asciidoctor.intellij.asciidoc, org.intellij.plugins.hcl, com.chrisrm.idea.MaterialThemeUI, io.github.satr.idea.plugin.connector.la, com.hotswap.agent.plugin, BashSupport, com.intellij.plugins.html.instantEditing, cucumber-javascript, izhangzhihao.rainbow.brackets, org.intellij.scala, org.jetbrains.plugins.vagrant, com.intellij.kubernetes, com.intellij.lang.puppet, com.zhaow.restful.toolkit, org.jeto.taskfocus, org.nik.presentation-assistant, org.scalafmt.ScalaFmt, org.zalando.intellij.swagger, ru.adelf.idea.dotenv, some.awesome
```

**OS:** 

```
OS X 10.14.6
iMac (Retina 5K, 27-inch, 2017)
4.2 GHz Intel Core i7
40 GB 2400 MHz DDR4
```

**Comment by partikus** [comment] 2019-08-12 08:00
The same issue occurs on Linux Ubuntu. 
Looks like the file does not exist in the given path: `backend/vendor/.gitignore` 

```
Error while indexing /home/partikus/Projects/.../backend/vendor/.gitignore
To reindex this file IDEA has to be restarted

java.lang.IllegalStateException: psiFile is null. language = Git, substitutedLanguage = Git
	at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:151)
	at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:140)
	at com.intellij.util.indexing.FileContentImpl.getFileFromText(FileContentImpl.java:108)
	at com.intellij.util.indexing.FileContentImpl.getPsiFileForPsiDependentIndex(FileContentImpl.java:276)
	at com.intellij.util.indexing.FileContentImpl.getPsiFile(FileContentImpl.java:96)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.map(IgnoreFilesIndex.java:86)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.map(IgnoreFilesIndex.java:59)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:313)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:108)
	at com.intellij.util.indexing.impl.MapReduceIndex.calculateUpdateData(MapReduceIndex.java:269)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:251)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1673)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$28(FileBasedIndexImpl.java:1603)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:634)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1562)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1549)
	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$indexFiles$0(UnindexedFilesUpdater.java:109)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$0(CacheUpdateRunner.java:219)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$1(CacheUpdateRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:232)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Frederick888** [comment] 2019-08-20 05:45
I wonder whether this is a bug or a feature... but either way it's quite annoying as every time I update my project dependencies, which contain .ignore files that I don't even want this plugin to analyse (and I actually have marked those directories as 'Excluded'), it immediately generates this exception and asks me to restart the IDE.

**Comment by cmshawns** [comment] 2019-08-20 17:13
This also started happening to me recently.

## Stack trace

```
Error while indexing C:\Users\<OneDrive path>\Documents\gitignore_global.txt
To reindex this file IDEA has to be restarted

java.lang.IllegalStateException: psiFile is null. language = Git, substitutedLanguage = Git
	at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:149)
	at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:138)
	at com.intellij.util.indexing.FileContentImpl.getFileFromText(FileContentImpl.java:106)
	at com.intellij.util.indexing.FileContentImpl.getPsiFileForPsiDependentIndex(FileContentImpl.java:274)
	at com.intellij.util.indexing.FileContentImpl.getPsiFile(FileContentImpl.java:94)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.map(IgnoreFilesIndex.java:86)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.map(IgnoreFilesIndex.java:59)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:312)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:109)
	at com.intellij.util.indexing.impl.MapReduceIndex.calculateUpdateData(MapReduceIndex.java:268)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:250)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1673)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$28(FileBasedIndexImpl.java:1603)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:656)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1562)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1549)
	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$indexFiles$0(UnindexedFilesUpdater.java:109)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$0(CacheUpdateRunner.java:219)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$1(CacheUpdateRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:232)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

## IDE

```
JetBrains Rider 2019.2.1
Build #RD-192.5895.1276, built on August 17, 2019
Licensed to Shawn South
Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1466M
Cores: 4
Registry: ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, ide.borderless.title.product=false, search.everywhere.configurations=false, performance.watcher.unresponsive.interval.ms=1000, ide.tooltip.initialDelay.highlighter=0, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, debugger.watches.in.variables=false, search.everywhere.toolwindows=false, ide.borderless.title.project.path=false, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.borderless.title.classpath=false, ide.require.transaction.for.model.changes=false
Non-Bundled Plugins: String Manipulation, XmlDocInspections, br.com.matheusfm.jsonutils, com.daylerees.rainglow, com.intellij.resharper.HeapAllocationsViewer, com.ppolivka.gitlabprojects, jms-messenger, main.kotlin.com.jimschubert.intellij.swaggercodegen, mobi.hsz.idea.gitignore, org.intellij.plugins.markdown, BashSupport, izhangzhihao.rainbow.brackets, com.intellij.plugin.adernov.powershell, org.zalando.intellij.swagger, uk.co.ben-gibson.remote.repository.mapper
```

## Windows

![image](https://user-images.githubusercontent.com/4257982/63368595-0ff56680-c333-11e9-8421-5ef722fc8027.png)

**Comment by thomasphansen** [comment] 2019-08-26 08:46
Same problem here, Linux Mint 19.2, existing intellij gradle project:
```
java.lang.IllegalStateException: psiFile is null. language = Git, substitutedLanguage = Git
	at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:149)
	at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:138)
	at com.intellij.util.indexing.FileContentImpl.getFileFromText(FileContentImpl.java:106)
	at com.intellij.util.indexing.FileContentImpl.getPsiFileForPsiDependentIndex(FileContentImpl.java:274)
	at com.intellij.util.indexing.FileContentImpl.getPsiFile(FileContentImpl.java:94)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.map(IgnoreFilesIndex.java:86)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.map(IgnoreFilesIndex.java:59)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:312)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:109)
	at com.intellij.util.indexing.impl.MapReduceIndex.calculateUpdateData(MapReduceIndex.java:268)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:250)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1673)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$28(FileBasedIndexImpl.java:1603)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:656)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1562)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1549)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1528)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1699)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1696)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:76)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:46)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1718)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:736)
	at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:892)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValueIterator(FileBasedIndexImpl.java:968)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:939)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:811)
	at org.zalando.intellij.swagger.index.openapi.OpenApiIndexService.isMainOpenApiFile(OpenApiIndexService.java:21)
	at org.zalando.intellij.swagger.file.icon.OpenApiIconProvider.isMain(OpenApiIconProvider.java:39)
	at org.zalando.intellij.swagger.file.icon.OpenApiIconProvider.getIcon(OpenApiIconProvider.java:26)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
	at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:101)
	at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$2(ElementBase.java:97)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:97)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:41)
	at com.intellij.ui.CoreIconManager.lambda$createDeferredIcon$0(CoreIconManager.java:38)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:263)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:151)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:126)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:93)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:150)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.lambda$run$0(BoundedTaskExecutor.java:185)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:181)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ruurd** [comment] 2019-08-28 09:13
Same on macOS 10.14.1

**Comment by dmitriysmirnovjb** [comment] 2019-08-28 09:16
The issue was caused by some indices incompatibility between old and new plugin versions. Likely, Invalidating caches via FIle - Invalidate Caches /Restart should help. 

6fc1461 adds some checks to avoid the exception. The fix will be included into the next plugin update.

**Closed by dmitriysmirnovjb** 2019-08-28 09:16 UTC

**Comment by thomasphansen** [comment] 2019-08-28 11:13
@dmitriysmirnovjb I've been invalidating and restarding for days now, and I always get the error again and again...
