### ISSUE TITLE
Not compatible with the Webstorm2020.2 Stable version.

### ISSUE THREAD

**Issue by MarxZhou** [JetBrains/idea-gitignore#633] opened 2020-07-28 01:58 UTC
### Prerequisites
Install the Webstorm2020.2 Stable version.

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description
I updated the Webstorm2020.2 Stable version in the first time. But the plug-in is found to be incompatible.
When I was upgrading the software, I was prompted by the editor that the current plug-in was not compatible.

### Steps to Reproduce

1. Install the Webstorm2020.2 Stable version.
2. Due to incompatibility issues, the current plugin cannot be searched in the plugin market.

**Expected behavior:**

The plugin can run in the latest version of webstrom.

**Actual behavior:** 

The plug-in cannot run.

**Reproduces how often:** 

Every time the editor is started.

### Versions

**Plugin:** 3.2.3.201

**IDE:** WebStorm 2020.2 Stable

**OS:** Windows 10

**Comment by ctharings** [comment] 2020-07-28 14:55
Duplicates #628

**Comment by SvenAugustus** [comment] 2020-07-29 02:04
2020.2 has released. update is going ?

**Comment by keeganwitt** [comment] 2020-07-29 02:32
> Duplicates #628

Related to that, I don't know if #630 will be re-purposed for the final release or what.

**Comment by MarxZhou** [comment] 2020-07-29 14:37
> 2020.2 has released. update is going ?

Directly prompt that the plug-in is not compatible with the current IDE.

**Comment by mozesa** [comment] 2020-07-30 07:20
**Hello**!

Same is true for `PyCharm 2020.2`.

![image](https://user-images.githubusercontent.com/49973426/88892935-e84a9600-d245-11ea-9e4c-cc59b38e7696.png)

**Comment by chinaerserver** [comment] 2020-07-30 12:14
Hello!

The same error for Idea2020.2.
![image](https://user-images.githubusercontent.com/19682865/88921464-2b862280-d2a1-11ea-926a-567965fd4e9d.png)
Plz fix it ,thx

**Comment by ZM-BAD** [comment] 2020-07-31 06:03
when will support intellij idea 2020.2 ?

**Comment by dmitriysmirnovjb** [comment] 2020-07-31 10:57
Duplicate of #628

**Closed by dmitriysmirnovjb** 2020-07-31 10:57 UTC
