### ISSUE TITLE
.Ignore not working for IntelliJ IDEA 2020.3

### ISSUE THREAD

**Issue by mehdimonemi** [JetBrains/idea-gitignore#644] opened 2020-12-06 09:07 UTC
The error text by the IntelliJ IDEA:
Plugin error: Plugin '.ignore' (version 'null') is not compatible with the current version of the IDE, because it requires build 203 or older but the current build is IU-203.5981.155

**Comment by mems** [comment] 2020-12-06 09:41
Duplicate #637

**Comment by dmitriysmirnovjb** [comment] 2020-12-06 19:26
Duplicate of #637

**Closed by dmitriysmirnovjb** 2020-12-06 19:26 UTC
