### ISSUE TITLE
Incompatibility with PyCharm 2020.3

### ISSUE THREAD

**Issue by mistrello96** [JetBrains/idea-gitignore#642] opened 2020-12-03 08:27 UTC
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [X] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

The plugin is not compatible with the latest version of PyCharm editor. The error reported is "Incompatible: requires IDE build 203 or older"

### Steps to Reproduce

1. Install the plugin
2. Update PyCharm to latest version (2020.3)
3. Restart the editor

**Reproduces how often:** 

Always

### Versions

**Plugin:** 

```
VERSION INFORMATION 3.2.3.202
```

```
IDE INFORMATION 2020.3
```

```
OS INFORMATION both windows and linux
```

**Comment by Ionaru** [comment] 2020-12-03 08:44
Duplicate of #637

**Closed** 2020-12-03 08:45 UTC
